
exports.up = function(knex) {
    return knex.schema.createTable('indger_reclama', table => {  
        table.increments('id').primary()
        table.integer('RECL_001')
        table.string('RECL_002',7)
        table.integer('RECL_003')
        table.integer('RECL_004')
        table.integer('RECL_005')
        table.integer('RECL_006')
        table.integer('RECL_007')
        table.integer('RECL_008')
        table.integer('RECL_009')
        table.integer('RECL_010')
        table.integer('RECL_011')
        table.integer('RECL_012')
        table.integer('RECL_013')
        table.integer('RECL_014')
        table.integer('RECL_015')
        table.integer('RECL_016')
        table.integer('RECL_017')
        table.integer('RECL_018')
        table.integer('RECL_019')
        table.integer('RECL_020')
        table.integer('RECL_021')
        table.integer('RECL_022')
        table.integer('RECL_023')
        table.integer('RECL_024')
        table.integer('RECL_025')
        table.integer('RECL_026')
        table.integer('RECL_027')
        table.integer('RECL_028')
        table.integer('RECL_029')
        table.integer('RECL_030')
        table.integer('RECL_031')
        table.integer('RECL_032')
        table.integer('RECL_033')
        table.integer('RECL_034')
        table.integer('RECL_035')
        table.integer('RECL_036')
        table.integer('RECL_037')
        table.integer('RECL_038')
        table.integer('RECL_039')
        table.integer('RECL_040')
        table.integer('RECL_041')
        table.integer('RECL_042')
        table.integer('RECL_043')
        table.integer('RECL_044')
        table.integer('RECL_045')
        table.integer('RECL_046')
        table.integer('RECL_047')
        table.integer('RECL_048')
        table.integer('RECL_049')
        table.integer('RECL_050')
        table.integer('RECL_051')
        table.integer('RECL_052')
        table.integer('RECL_053')
    })
  
};

exports.down = function(knex) {
    return knex.schema.dropTable('indger_reclama')
};
